# Needs DigitalOcean module for Caddy
# see: https://github.com/caddy-dns/digitalocean

FROM caddy:builder-alpine AS builder

RUN xcaddy build \
    --with github.com/RussellLuo/caddy-ext/ratelimit

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
