version: "3.8"

services:
    caddy:
        # see https://hub.docker.com/_/caddy
        container_name: caddy
        image: "caddy:alpine"
        init: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/dist:/static
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - api

    api:
        container_name: transfer
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: transfer:latest
        init: true
        shm_size: 100mb
        environment:
            - ROOT_PATH=/api
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
