services:

    caddy:
        container_name: caddy
        build:
            context: .
            dockerfile: Dockerfile.caddy
        image: "custom-caddy:latest"
        init: true
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - transfer
        restart: unless-stopped
        environment:
            - ENV=${ENV:-production}

    transfer:
        container_name: transfer
        image: transfer:latest
        build:
            context: .
        init: true
        ports:
            - "5000:5000"
        restart: unless-stopped
        environment:
            ENV: ${ENV:-development}
        volumes:
            - .:/app
        command:
            [
                "hypercorn",
                "--config",
                "hypercorn.toml",
                "--reload",
                "transfer.main:app"
            ]
