version: "3.9"

services:

    caddy:
        container_name: caddy
        image: "caddy:alpine"
        init: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - transfer
            - redis

    redis:
        container_name: redis
        image: redis:latest
        init: true
        ports:
            - ${REDIS_PORT:-6379}:6379

    transfer:
        container_name: transfer
        image: transfer:latest
        build:
            context: .
        init: true
        ports:
            - "5000:5000"
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
